### ISSUE TITLE
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

### ISSUE THREAD

**Issue by zuozc** [softlayer/softlayer-python#798]
I tried to list my SL machines using command `slcli hw list -H "prod1*"`, but failed after I upgraded my slcli to 5.2.1. The command could fulfill my request before the upgrade. My previous slcli version is 4.1.1 by the way. This seems would happen every time the slcli command needs to be authenticated. Could you please take a look? Thank you.

### Expected Behavior

It should return my machine list starting with "prod" or give me a credential related error.

### Actual Behavior

It returns following errors.

```slcli hw list -H "prod1*"
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/core.py", line 163, in main
    cli.main(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/CLI/hardware/list.py", line 78, in cli
    mask=columns.mask())
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/managers/hardware.py", line 170, in list_hardware
    return self.account.getHardware(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 392, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 360, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 331, in __call__
    result = self.transport(call)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 168, in __call__
    proxies=_proxies_dict(self.proxy))
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
```

### Environment Information
Operating System: MacOS Sierra 10.12.1
softlayer-python version (`slcli --version`): 5.2.1
python version: 2.7.10

**Comment by zuozc** [comment]
This issue got fixed after I upgraded `cryptography` to the latest version.
This is what I had referenced to https://github.com/kennethreitz/requests/issues/3710.

**Comment by camporter** [comment]
I'm going to go ahead and close this issue since the problem was with another module.
